version: 2.1
description: >
  Executing Katalon tests with your CircleCI CI/CD pipeline easily with the Katalon orb
display:
  home_url: https://docs.katalon.com/katalon-studio/docs/integration-circleci.html
  source_url: https://github.com/katalon-studio/katalon-circleci-orb
orbs:
     katalon-studio: katalon/katalon-studio@23.0.12 #replace 23.0.12 with the latest version of Katalon Orb
workflows:
       build:
        jobs:
            - katalon-studio/run:
                    version: "latest"
                    command_arguments: "-browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test Suites/Verify Operations'"